# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/FPGA/My_FPGA/TCL_project/Prj/Instrument/user/Hardware/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
# IP: The module: 'zynq_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/FPGA/My_FPGA/TCL_project/Prj/Instrument/user/Hardware/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/project/FPGA/My_FPGA/TCL_project/Prj/Instrument/user/Hardware/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
# IP: The module: 'zynq_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/FPGA/My_FPGA/TCL_project/Prj/Instrument/user/Hardware/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
